# Generated by Django 2.1 on 2020-05-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameManager', '0002_player_playername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=16, unique=True)),
                ('rommPassword', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='playerName',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
