# Generated by Django 2.1 on 2020-05-14 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameManager', '0003_auto_20200508_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='playerName',
        ),
        migrations.AddField(
            model_name='player',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
