# Generated by Django 2.1 on 2020-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameManager', '0004_auto_20200514_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerName',
            field=models.CharField(default='example player', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
