# Generated by Django 2.1 on 2020-05-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameManager', '0005_player_playername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerName',
            field=models.CharField(max_length=16),
        ),
    ]
