# Generated by Django 2.1 on 2020-05-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameManager', '0006_auto_20200520_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerName',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
